### ISSUE TITLE
Is this thing on?

### ISSUE THREAD

**Issue by iamjolly** [18F/portfolios#13]
## Expected Behavior

@stvnrlly will get a note in Slack.

## Actual Behavior

Let's see what happens

## Steps to reproduce the behavior
- [ ] Open an issue
- [ ] Check the Slack channel #portfolio-site
- [ ] Is there a notice

## This issue is done when:
- [ ] @stvnrlly comes here and closes this issue.

**Comment by stvnrlly** [comment]
hi
